// services/depositMonitor.js
// PRAQEN — Automatic Bitcoin Deposit Monitor
// Runs as a background job inside server.js
// Polls every 60 seconds for new deposits to ALL user wallets
// When deposit found → updates DB balance → notifies user

require('dotenv').config();
const axios  = require('axios');
const { createClient } = require('@supabase/supabase-js');
const hdWallet = require('./hdWalletService');

// ── Supabase admin client ─────────────────────────────────────────────────────
const supabaseAdmin = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY
);

// ── Config ────────────────────────────────────────────────────────────────────
const POLL_INTERVAL_MS    = 60 * 1000;   // check every 60 seconds
const MIN_CONFIRMATIONS   = 1;           // 1 confirmation = safe to credit
const DUST_THRESHOLD_SATS = 546;         // ignore dust below this

class DepositMonitor {

  constructor() {
    this.isRunning    = false;
    this.intervalId   = null;
    this.network      = null;
    this.apiBase      = null;
    this.checkedTxIds = new Set(); // in-memory cache to avoid double-crediting
  }

  // ── Start the background monitor ─────────────────────────────────────────
  start() {
    if (this.isRunning) {
      console.log('⚠️  DepositMonitor already running');
      return;
    }

    this.network = process.env.HD_NETWORK || 'testnet';
    this.apiBase = this.network === 'mainnet'
      ? 'https://mempool.space/api'
      : 'https://mempool.space/testnet/api';

    console.log(`\n🔍 DepositMonitor started — ${this.network.toUpperCase()}`);
    console.log(`   Polling every ${POLL_INTERVAL_MS / 1000}s`);
    console.log(`   API: ${this.apiBase}\n`);

    this.isRunning = true;

    // Run immediately on start, then on interval
    this.checkAllDeposits();
    this.intervalId = setInterval(() => this.checkAllDeposits(), POLL_INTERVAL_MS);
  }

  // ── Stop the monitor ──────────────────────────────────────────────────────
  stop() {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    this.isRunning = false;
    console.log('🛑 DepositMonitor stopped');
  }

  // ── Check all user wallets for new deposits ───────────────────────────────
  async checkAllDeposits() {
    try {
      // Get all users who have a wallet address
      const { data: users, error } = await supabaseAdmin
        .from('users')
        .select('id, username, bitcoin_wallet_address')
        .not('bitcoin_wallet_address', 'is', null)
        .neq('bitcoin_wallet_address', '');

      if (error) {
        console.error('[DepositMonitor] Failed to fetch users:', error.message);
        return;
      }

      if (!users || users.length === 0) {
        console.log('[DepositMonitor] No wallets to monitor yet');
        return;
      }

      console.log(`[DepositMonitor] Checking ${users.length} wallets...`);

      // Check each user wallet (with a small delay between each to avoid rate limits)
      for (const user of users) {
        await this.checkUserDeposit(user);
        await this.sleep(500); // 500ms delay between calls
      }

    } catch (error) {
      console.error('[DepositMonitor] Unexpected error:', error.message);
    }
  }

  // ── Validate a Bitcoin address is real (not a mock hex string) ──────────
  isValidBitcoinAddress(address) {
    if (!address || typeof address !== 'string') return false;
    const network = process.env.HD_NETWORK || 'testnet';

    if (network === 'testnet') {
      // Testnet SegWit MUST start with tb1 and be lowercase bech32
      // Fake mock addresses are uppercase hex — they fail this check
      return /^tb1[a-z0-9]{25,87}$/.test(address);
    } else {
      // Mainnet SegWit starts with bc1 (lowercase bech32)
      // Legacy starts with 1 or 3 but contains mixed case base58
      if (address.startsWith('bc1')) {
        return /^bc1[a-z0-9]{25,87}$/.test(address);
      }
      // Legacy — reject if all uppercase (fake hex)
      if (/^[0-9A-F]{20,}$/.test(address)) return false;
      return /^[13][a-zA-HJ-NP-Z1-9]{25,34}$/.test(address);
    }
  }

  // ── Check a single user's wallet for new deposits ─────────────────────────
  async checkUserDeposit(user) {
    const { id: userId, username, bitcoin_wallet_address: address } = user;

    if (!address) return;

    // ── Skip fake/mock addresses generated by old system ──────────────────
    if (!this.isValidBitcoinAddress(address)) {
      console.log(`[DepositMonitor] ⚠️  Skipping ${username} — fake address detected: ${address.slice(0,16)}…`);
      console.log(`[DepositMonitor]    Generating real HD address for ${username}...`);

      // Auto-upgrade: generate real HD address for this user
      try {
        const hdWallet = require('./hdWalletService');
        const real     = hdWallet.generateUserAddress(userId);

        await supabaseAdmin
          .from('users')
          .update({
            bitcoin_wallet_address: real.address,
            updated_at: new Date().toISOString(),
          })
          .eq('id', userId);

        console.log(`[DepositMonitor] ✅ Real address saved for ${username}: ${real.address}`);
      } catch (upgradeErr) {
        console.error(`[DepositMonitor] Failed to upgrade address for ${username}:`, upgradeErr.message);
      }
      return; // Skip monitoring this cycle — will monitor next cycle with real address
    }

    try {
      // Get transactions for this address from mempool
      const response = await axios.get(
        `${this.apiBase}/address/${address}/txs`,
        { timeout: 15000 }
      );

      const txs = response.data || [];
      if (txs.length === 0) return;

      // Get current tracked balance from DB
      const { data: balanceRow } = await supabaseAdmin
        .from('user_balances')
        .select('balance_btc')
        .eq('user_id', userId)
        .single();

      const currentBalance = parseFloat(balanceRow?.balance_btc || 0);

      // Process each transaction
      for (const tx of txs) {
        const txid = tx.txid;

        // Skip if we already processed this tx
        if (this.checkedTxIds.has(`${userId}_${txid}`)) continue;

        // Skip unconfirmed transactions
        const confirmations = tx.status?.confirmed ? 1 : 0;
        if (confirmations < MIN_CONFIRMATIONS) {
          console.log(`[DepositMonitor] TX ${txid.slice(0,12)}… pending for ${username}`);
          continue;
        }

        // Check if this TX was already credited in DB
        const { data: existingTx } = await supabaseAdmin
          .from('wallet_transactions')
          .select('id')
          .eq('user_id', userId)
          .eq('tx_hash', txid)
          .eq('type', 'DEPOSIT')
          .maybeSingle();

        if (existingTx) {
          // Already credited — mark as checked in memory
          this.checkedTxIds.add(`${userId}_${txid}`);
          continue;
        }

        // Calculate how much BTC this TX sent TO our user's address
        let depositSats = 0;
        for (const vout of (tx.vout || [])) {
          if (vout.scriptpubkey_address === address) {
            depositSats += vout.value;
          }
        }

        if (depositSats <= DUST_THRESHOLD_SATS) continue;

        const depositBTC = depositSats / 1e8;

        console.log(`\n💰 [DepositMonitor] New deposit detected!`);
        console.log(`   User:    ${username} (${userId.slice(0,8)})`);
        console.log(`   TX:      ${txid.slice(0,16)}…`);
        console.log(`   Amount:  ${depositBTC} BTC`);

        // Credit the user's balance
        const newBalance = currentBalance + depositBTC;

        const { error: balErr } = await supabaseAdmin
          .from('user_balances')
          .upsert({
            user_id:    userId,
            balance_btc: newBalance,
            updated_at: new Date().toISOString(),
          });

        if (balErr) {
          console.error(`[DepositMonitor] Failed to update balance for ${username}:`, balErr.message);
          continue;
        }

        // Log the deposit transaction
        await supabaseAdmin
          .from('wallet_transactions')
          .insert({
            user_id:    userId,
            type:       'DEPOSIT',
            amount_btc: depositBTC,
            status:     'CONFIRMED',
            tx_hash:    txid,
            created_at: new Date().toISOString(),
          });

        // Send in-app notification
        await supabaseAdmin
          .from('notifications')
          .insert({
            user_id:    userId,
            type:       'wallet',
            title:      '₿ Bitcoin Received!',
            message:    `${depositBTC.toFixed(8)} BTC has been credited to your PRAQEN wallet. New balance: ${newBalance.toFixed(8)} BTC`,
            action:     '/wallet',
            is_read:    false,
            created_at: new Date().toISOString(),
          });

        // Mark as processed in memory
        this.checkedTxIds.add(`${userId}_${txid}`);

        console.log(`✅ [DepositMonitor] Credited ${depositBTC} BTC to ${username}`);
        console.log(`   New balance: ${newBalance.toFixed(8)} BTC\n`);
      }

    } catch (error) {
      // Don't crash the whole monitor if one user fails
      if (error.response?.status === 429) {
        console.warn(`[DepositMonitor] Rate limited — will retry ${username} next cycle`);
      } else {
        console.error(`[DepositMonitor] Error checking ${username}:`, error.message);
      }
    }
  }

  // ── Check a specific address manually (used by API endpoint) ─────────────
  async checkAddressNow(userId) {
    try {
      const { data: user, error } = await supabaseAdmin
        .from('users')
        .select('id, username, bitcoin_wallet_address')
        .eq('id', userId)
        .single();

      if (error || !user) throw new Error('User not found');
      if (!user.bitcoin_wallet_address) throw new Error('No wallet address found');

      console.log(`[DepositMonitor] Manual check for ${user.username}`);
      await this.checkUserDeposit(user);

      // Return current balance after check
      const { data: bal } = await supabaseAdmin
        .from('user_balances')
        .select('balance_btc')
        .eq('user_id', userId)
        .single();

      return {
        success:     true,
        balance_btc: parseFloat(bal?.balance_btc || 0),
        address:     user.bitcoin_wallet_address,
        checked_at:  new Date().toISOString(),
      };

    } catch (error) {
      console.error('[DepositMonitor] Manual check failed:', error.message);
      throw error;
    }
  }

  // ── Also monitor escrow addresses for active trades ───────────────────────
  async checkEscrowDeposits() {
    try {
      // Get all active trades that are waiting for BTC deposit
      const { data: trades, error } = await supabaseAdmin
        .from('trades')
        .select('id, buyer_id, seller_id, amount_btc, escrow_wallet_address, status')
        .in('status', ['CREATED', 'PENDING_DEPOSIT'])
        .not('escrow_wallet_address', 'is', null);

      if (error || !trades || trades.length === 0) return;

      console.log(`[DepositMonitor] Checking ${trades.length} escrow addresses...`);

      for (const trade of trades) {
        await this.checkEscrowFunded(trade);
        await this.sleep(500);
      }

    } catch (error) {
      console.error('[DepositMonitor] Escrow check error:', error.message);
    }
  }

  // ── Check if an escrow address has been funded ────────────────────────────
  async checkEscrowFunded(trade) {
    const { id: tradeId, escrow_wallet_address: address, amount_btc } = trade;

    if (!address) return;

    try {
      const response = await axios.get(
        `${this.apiBase}/address/${address}`,
        { timeout: 15000 }
      );

      const data = response.data;
      const confirmedSats = data.chain_stats.funded_txo_sum - data.chain_stats.spent_txo_sum;
      const confirmedBTC  = confirmedSats / 1e8;
      const requiredBTC   = parseFloat(amount_btc || 0);

      if (confirmedBTC >= requiredBTC && requiredBTC > 0) {
        console.log(`\n🔒 [DepositMonitor] Escrow funded for trade ${tradeId.slice(0,8)}`);
        console.log(`   Required: ${requiredBTC} BTC`);
        console.log(`   Received: ${confirmedBTC} BTC`);

        // Update trade status to FUNDS_LOCKED
        await supabaseAdmin
          .from('trades')
          .update({
            status:           'FUNDS_LOCKED',
            escrow_locked_at: new Date().toISOString(),
            escrow_amount:    confirmedBTC,
          })
          .eq('id', tradeId)
          .in('status', ['CREATED', 'PENDING_DEPOSIT']);

        // Notify both buyer and seller
        for (const uid of [trade.buyer_id, trade.seller_id]) {
          await supabaseAdmin.from('notifications').insert({
            user_id:    uid,
            type:       'trade',
            title:      '🔒 Escrow Funded!',
            message:    `Trade #${tradeId.slice(0,8).toUpperCase()} is now ACTIVE. Bitcoin locked in escrow.`,
            action:     `/trade/${tradeId}`,
            is_read:    false,
            created_at: new Date().toISOString(),
          });
        }

        console.log(`✅ [DepositMonitor] Trade ${tradeId.slice(0,8)} is now ACTIVE\n`);
      }

    } catch (error) {
      console.error(`[DepositMonitor] Escrow check error for trade ${tradeId.slice(0,8)}:`, error.message);
    }
  }

  // ── Helper: sleep ─────────────────────────────────────────────────────────
  sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  // ── Status info ───────────────────────────────────────────────────────────
  getStatus() {
    return {
      running:          this.isRunning,
      network:          this.network,
      poll_interval_s:  POLL_INTERVAL_MS / 1000,
      txs_tracked:      this.checkedTxIds.size,
      api:              this.apiBase,
    };
  }
}

// Export a single instance
module.exports = new DepositMonitor();